#!/usr/bin/env python3
"""
Lists the public API without documentation, as dox sees it: reads the
docs/api/heaps_*.xml files (generate them first with build-api.sh or the
docs/api/xml-*.hxml files), so it also catches docs that Haxe drops, like
a type doc placed after its metadata.
Usage: python3 tools/docgen/xml-undocumented.py [package prefix ...]
Prints `file  Type.field` for each undocumented type, field or enum
constructor (documented on no platform), then the count.
"""
import glob, os, sys
import xml.etree.ElementTree as ET

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
PREFIXES = sys.argv[1:] or ["h2d", "h3d", "hxd", "hxsl"]
HIDE = (":dox", ":noCompletion", ":compilerGenerated", ":deprecated")


def hidden(e):
    return any(m.get("n") in HIDE for m in e.findall("meta/m"))


_lines = {}


def source_line(file, line):
    if file not in _lines:
        try:
            _lines[file] = open(file, encoding="utf-8", errors="replace").read().split("\n")
        except OSError:
            _lines[file] = []
    return _lines[file][line - 1] if 0 < line <= len(_lines[file]) else ""


def doc(e):
    return bool((e.findtext("haxe_doc") or "").strip())


found, documented, files = set(), set(), {}
parents = {}
for xml in glob.glob(os.path.join(ROOT, "docs", "api", "heaps_*.xml")):
    for t in ET.parse(xml).getroot():
        e = t.find("extends")
        if e is not None:
            parents[t.get("path")] = e.get("path")


def is_shader(path):
    while path:
        if path == "hxsl.Shader":
            return True
        path = parents.get(path)
    return False



def add(key, e, file):
    found.add(key)
    files.setdefault(key, file)
    if doc(e):
        documented.add(key)


for xml in sorted(glob.glob(os.path.join(ROOT, "docs", "api", "heaps_*.xml"))):
    for t in ET.parse(xml).getroot():
        path = t.get("path") or ""
        if t.get("private") == "1" or not any(path == p or path.startswith(p + ".") for p in PREFIXES):
            continue
        if hidden(t):
            continue
        file = os.path.relpath(t.get("file") or "", ROOT)
        add(path, t, file)
        if t.tag == "typedef":
            anon = t.find("a")
            members = list(anon) if anon is not None else []
        elif t.tag == "abstract":
            impl = t.find("impl/class")
            members = list(impl) if impl is not None else []
        else:
            members = list(t)
        overrides = {o.get("n") for o in t.findall("overrides/x")} if t.find("overrides") is not None else set()
        for f in members:
            if f.tag in ("haxe_doc", "meta", "implements", "extends", "overloads", "impl", "overrides", "this", "from", "to") or f.tag.startswith("_"):
                continue
            if t.tag in ("class", "abstract") and f.get("public") != "1":
                continue
            if hidden(f) or f.tag in overrides or f.get("override") == "1" or f.tag.startswith(("get_", "set_")):
                continue
            # generated by macros: hxsl shader members (no position), BitsBuilder constants
            if f.get("line") is None and is_shader(path) or f.tag.endswith(("_bits", "_mask", "_offset")) and f.get("static") == "1":
                continue
            # constructor inherited by a class that declares none: positioned on the class
            if f.tag == "new" and f.get("line") and "class " in source_line(t.get("file"), int(f.get("line"))):
                continue
            # BitsBuilder getters
            if f.get("static") == "1" and f.get("get") == "inline" and len(f.tag) > 3 and f.tag.startswith("get") and t.find(f.tag[3].lower() + f.tag[4:] + "_bits") is not None:
                continue
            add(path + "." + f.tag, f, file)

missing = sorted(found - documented, key=lambda k: (files[k], k))
for k in missing:
    print(f"{files[k]}  {k}")
print(f"{len(missing)} undocumented")
