package hxsl;

/**
	The base class of the shaders generated by `hxsl.Cache.makeBatchShader`, which read the per-instance parameters of a batch from a buffer.
**/
class BatchShader extends hxsl.Shader {

	static var SRC = {
		@const var Batch_HasOffset : Bool;
		@const var Batch_UseStorage : Bool;
		@const(4096) var Batch_Count : Int;
		@param var Batch_Buffer : Buffer<Vec4,Batch_Count>;
		@param var Batch_StorageBuffer : RWBuffer<Vec4>;
	};

	/**
		The parameters read from the buffer.
	**/
	public var params : RuntimeShader.AllocParam;
	/**
		The size of the parameters of an instance, in vec4.
	**/
	public var paramsSize : Int;

}