package hxd;

#if !macro
@:build(hxd.res.FileTree.build())
#end
/**
	The access point to the resources (the files of the `res` directory). Its fields are generated by a macro from the
	resource files: `hxd.Res.my.image` is the resource `res/my/image.png`.

	Initialize the resource loader once, before accessing resources:

	```haxe
	hxd.Res.initEmbed(); // resources embedded in the binary
	var tile = hxd.Res.hero.toTile();
	```
**/
class Res {

	#if !macro
	/**
		Loads the resource of the given path (relative to the resources directory).
	**/
	public static function load(name:String) {
		return loader.load(name);
	}
	#end

	/**
		Initializes the loader with the resources embedded in the binary (all platforms).
	**/
	public static macro function initEmbed(?options:haxe.macro.Expr.ExprOf<hxd.res.EmbedOptions>) {
		return macro hxd.Res.loader = new hxd.res.Loader(hxd.fs.EmbedFileSystem.create(null,$options));
	}

	/**
		Initializes the loader with the files of the resources directory on disk (desktop and Node.js), which allows hot reloading.
		The directory is `res` or the `-D resourcesPath=...` value.
		@param configuration The configuration used to convert the resources (see `hxd.fs.Convert`).
	**/
	public static macro function initLocal( ?configuration : String ) {
		var dir = haxe.macro.Context.definedValue("resourcesPath");
		if( dir == null ) dir = "res";
		dir = haxe.macro.Context.resolvePath(dir);
		return macro hxd.Res.loader = new hxd.res.Loader(new hxd.fs.LocalFileSystem($v{dir},$v{configuration}));
	}

	/**
		Initializes the loader with resources packed in `.pak` files (see `hxd.fmt.pak`).
	**/
	public static macro function initPak( ?file : String ) {
		if( file == null )
			file = haxe.macro.Context.definedValue("resourcesPath");
		if( file == null )
			file = "res";
		return macro {
			var file = $v{file};
			var pak = new hxd.fmt.pak.FileSystem();
			pak.loadPak(file + ".pak");
			var i = 1;
			while( true ) {
				if( !hxd.File.exists(file + i + ".pak") ) break;
				pak.loadPak(file + i + ".pak");
				i++;
			}
			hxd.Res.loader = new hxd.res.Loader(pak);
		}
	}

}
